backend:
  name: git-gateway
  branch: main

media_folder: public/images/uploads
public_folder: /images/uploads

collections:
  - name: blog
    label: Blog
    folder: src/content/blog
    create: true
    slug: "{{slug}}"
    fields:
      - label: Title
        name: title
        widget: string
      - label: Publish Date
        name: date
        widget: datetime
      - label: Description
        name: description
        widget: text
      - label: Cover Image
        name: cover
        widget: image
        required: false
      - label: Body
        name: body
        widget: markdown

  - name: travel
    label: Travel
    folder: src/content/travel
    create: true
    slug: "{{slug}}"
    fields:
      - label: Title
        name: title
        widget: string
      - label: Location
        name: location
        widget: string
      - label: Date
        name: date
        widget: datetime
      - label: Photos
        name: photos
        widget: list
        field:
          label: Photo
          name: photo
          widget: image
      - label: Body
        name: body
        widget: markdown
